import Head from 'next/head'
import Link from 'next/link'
// import { useState, useEffect } from 'react'
import Header from '../components/Header'
import AddButton from '../components/AddButton'
import ArsipButton from '../components/ArsipButton'
import NoteList from '../components/NoteList'

export default function Home({dataNote}) {

  // const [dataNote, setNote] = useState([])

  //   useEffect(() => {
  //       fectData()
  //   }, []);

  //   const fectData = async() => {
  //     const response = await fetch('http://localhost:5000/note');
  //     const data =  await response.json();
  //     setNote(data);
  // }
    const filterArchive = 
        dataNote.filter(function (el) {
            return el.archive === true
        });
    
    console.log(filterArchive);

  return (
    
    <div>
      {/* <Head>
        <title>XRC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
        <div className='w-full'>
            <ul className='grid grid-cols-2 grid-flow-row-dense gap-2'>
                { filterArchive.map(item => (
                    <Link className='' key={item.id} href={`/edit/${item.id}`}>
                        <li key={item.id} className="max-h-52 overflow-hidden p-3 border-2 border-darkLighter rounded-md z-10">
                            <h1 className='text-sm font-semibold mb-1.5 leading-none'>{item.title}</h1>
                            <div className='pb-3 max-h-38 overflow-hidden demo-3'>
                                <p className='text-xs text-[#999] leading-tight'>{item.textNote}</p>
                            </div>
                            {/* <button onClick={() => hapusNote(item.id)}>Delete</button> */}
                        </li>
                    </Link>
                ))}
            </ul>
        </div>

      
       

    </div>
  )
}

export const getServerSideProps = async () =>{
  const response = await fetch("https://6347b41a0484786c6e8665bf.mockapi.io/notes");
  const data = await response.json();

  return {
    props : {
      dataNote : data
    }
  }
}

// export const getServerSideProps = async () => {
//   const response = await fetch("http://localhost:5000/note");
//   const data = await response.json();
//   return {
//     props:{
//       products: data
//     }
     
//   }
// }