import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>XRC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen flex flex-col items-center justify-center ">
        <h1 className='text-2xl font-semibold'>Hello, world! iam rianlauo</h1>
        <p>Project with Next.js & tailwindcss</p>
      </main>  
    </div>
  )
}
