import Head from 'next/head'
import Link from 'next/link'
import AddButton from '../components/AddButton'
import NoteList from '../components/NoteList'

export default function Home() {
  return (
    
    <div className="max-w-md mx-auto px-4 py-5 overflow-x-hidden">
      <Head>
        <title>XRC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NoteList/>
      <Link href="/addnote" passHref>
        <AddButton />
      </Link>

    </div>
  )
}


// export const getServerSideProps = async () => {
//   const response = await fetch("https://my-json-server.typicode.com/rianllauo/fakeapi/data");
//   const data = await response.json();
//   return {
//     props:{
//       products: data
//     }
     
//   }
// }